// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBixmSBxLWBllanZndvBaVr7gCdJQk0IlU',
    appId: '1:902978173207:web:b51283d1ee89658e1d1f52',
    messagingSenderId: '902978173207',
    projectId: 'realty-3c993',
    authDomain: 'realty-3c993.firebaseapp.com',
    storageBucket: 'realty-3c993.firebasestorage.app',
    measurementId: 'G-YH3B71B9V3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXzg_Z7RuHSLmjziYbcmXEVMbQSaocEeA',
    appId: '1:902978173207:android:329cd8ea4cf296da1d1f52',
    messagingSenderId: '902978173207',
    projectId: 'realty-3c993',
    storageBucket: 'realty-3c993.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByAK6MrAds6NsTB2UfccuUZd2qHHsinh0',
    appId: '1:902978173207:ios:c401776b379521791d1f52',
    messagingSenderId: '902978173207',
    projectId: 'realty-3c993',
    storageBucket: 'realty-3c993.firebasestorage.app',
    iosBundleId: 'com.example.realtorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByAK6MrAds6NsTB2UfccuUZd2qHHsinh0',
    appId: '1:902978173207:ios:c401776b379521791d1f52',
    messagingSenderId: '902978173207',
    projectId: 'realty-3c993',
    storageBucket: 'realty-3c993.firebasestorage.app',
    iosBundleId: 'com.example.realtorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBixmSBxLWBllanZndvBaVr7gCdJQk0IlU',
    appId: '1:902978173207:web:0cf35055eef3cddf1d1f52',
    messagingSenderId: '902978173207',
    projectId: 'realty-3c993',
    authDomain: 'realty-3c993.firebaseapp.com',
    storageBucket: 'realty-3c993.firebasestorage.app',
    measurementId: 'G-T3L383S9WE',
  );

}